name: Deploy Back-End

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'amazon corretto'
          java-version: '21'

      - name: Construir a aplicação
        run: |
          mvn clean package -DskipTests

      - name: Deploy na Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: backend-app-ecommerce
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: target/*.jar
