name: Deploy Front-End

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm install

      - name: Construir o projeto
        run: npm run build

      - name: Login na Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy na Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: frontend-app-ecommerce
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: build

